### PR TITLE
Added some better and more accurate on how to return errors

### PR DESCRIPTION
**Pull request by lsv**
Some improved docs on how to generate errors.
To reference #207

### CODE REVIEW

**Comment by JHGitty** [comment]
Thank you for this documentation - really helpful. Would be interesting if there is any easy "default" way to delete a file on error (shouldn't this be done automatically on exceptions?).

**Comment by lsv** [comment]
@JHGitty I think its OK, to leave the file, if you dont want the file should be touched, then just use the validation method.

The problem with the validation method, its only for Dropzone and Blueimp, and I dont think that ```unlink($event->getFile())``` is a problem to run

**Comment by JHGitty** [comment]
Oh.. any idea how I may do it for FineUploader?

**Comment by lsv** [comment]
First make a [ErrorHandler](https://github.com/1up-lab/OneupUploaderBundle/tree/master/Uploader/ErrorHandler) for Fineuploader so you use the validation method, then add it to [the config](https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/config/errorhandler.xml) and it seems like the fineuploader already can handle errors in the controller.

**Comment by bytehead** [comment]
@lsv Thanks for your contribution!

**Pull request merged**
