### PR TITLE
Replaced deprecated global Twig functions

### PR DESCRIPTION
**Pull request by KoenvanWijnen**
Updated the UploaderExtension so it's supports Twig 3.0.
Also had to add Twig to the composer requirement because it was not there yet.

### CODE REVIEW

**Comment by Holicz** [comment]
Is anything blocking the merge of this PR? I am ready to help.

**Comment by bytehead** [comment]
The tests are failing, I've to check this first. I don't know if it's related to this changes.

**Comment by bytehead** [comment]
@Holicz I've looked into the tests. They're failing because of Symfony > 4.1, see also #364.

**Comment by bytehead** [comment]
@KoenvanWijnen can you rebase your PR with the actual master? It possibly fixes the tests. :-)

**Comment by KoenvanWijnen** [comment]
> @KoenvanWijnen can you rebase your PR with the actual master? It possibly fixes the tests. :-)

All done

**Comment by bytehead** [comment]
Looks good! 🎉

**Comment by bytehead** [comment]
Thank you!

**Pull request merged**
