### PR TITLE
Added league/flysystem to also be a possible filesystem

### PR DESCRIPTION
**Pull request by lsv**
Integrated [Flysystem](https://github.com/1up-lab/OneupFlysystemBundle) so not only gaufrette is a option

### CODE REVIEW

**Comment by lsv** [comment]
Could someone test it with s3?

I will also write some documentation on how to use it, if accepted

**Comment by lsv** [comment]
Tested with
- Local
- Dropbox
- Orphange

**Comment by bytehead** [comment]
Hi @lsv ! Thanks for your PR, looks really good to me. And thanks for testing! My bad, that I can't test it with s3...

**Comment by lsv** [comment]
The failed tests are PHP 5.3 as flysystem requires PHP 5.4
I would suggest not support 5.3 anymore?

**Comment by bytehead** [comment]
Yes, I saw it. I would say we can skip 5.3 due to the fact that 5.3 is EOL since 14th of august 2014.

**Comment by lsv** [comment]
And the reason for using flysystem imo gaufrette is somekind of dead, and lot of other bundles are using flysystem instead.

**Comment by bytehead** [comment]
Can you drop the 5.3 support in `travis.yml` within this PR?

**Comment by rvmourik** [comment]
Is there an estimate when this fork will be merged? I'm looking forward in using flysystem with this bundle

**Comment by bytehead** [comment]
@rvmourik [1.5.0](https://github.com/1up-lab/OneupUploaderBundle/releases/tag/1.5.0) is out :)

**Comment by rvmourik** [comment]
@bytehead Thanks, that was pretty quick :-)

**Comment by bytehead** [comment]
It was on my list for at least 8 days ;-)

**Comment by bytehead** [comment]
@lsv: @sheeep is pretty happy about your PR and much thanks from him as well! :tada:

**Comment by Sander-Toonen** [comment]
Wow, this is very good news! It might need some documentation though.

Is it as straightforward as replacing gaufrette with flysystem? Does it support chunked uploading?

**Comment by lsv** [comment]
When I have a few moments i will write a proper documentation.

But for short, change gaufrette to flysystem in storage type.
And then setup [https://github.com/1up-lab/OneupFlysystemBundle](flysystem bundle)

**Comment by lsv** [comment]
@bytehead well it actually took some time for me to find out that 1up-lab also have flysystem bundle, so I was a bit confused why you have chosen gaufrette :)

Anyways, it was actually pretty easy to create this, when I figured out that FileInterface missing a few methods, like move() and so on - I will properly make a PR for this.

And also a PR for documentation will come in a near future

**Comment by bytehead** [comment]
@lsv I can totally understand your confusion :smile: 
The uploader bundle came out way before our flysystem bundle - that's probably why it ended up like this...

Sounds great - your PRs are always welcome!

**Comment by SrgSteak** [comment]
I get a OutOfMemoryException on oneup/uploader-bundle/Oneup/UploaderBundle/Uploader/Storage/FlysystemStorage.php line 47 when uploading a larger file (~400MB). The chunked upload works, but the last step seems to cause the exception.

Any ideas?

**Pull request merged**
