### PR TITLE
Remove useless argument

### PR DESCRIPTION
**Pull request by ErnadoO**
https://github.com/1up-lab/OneupUploaderBundle/pull/373#issuecomment-589233366

image

### CODE REVIEW

**Comment by bytehead** [comment]
You should add the argument `ChunkStorage $chunkStorage` there instead. `FilesystemOrphanageStorage` and `GaufretteOrphanageStorage` have one too.

**Comment by ErnadoO** [comment]
> FilesystemOrphanageStorage

FlysystemOrphanageStorage you mean ?

So, why remove this argument from FilesystemOrphanageStorage in [this commit](https://github.com/1up-lab/OneupUploaderBundle/pull/373/commits/92e963d1a5a332ddb246db2f3a25ff25c3dd2c6b) ? a mistake ?

**Comment by bytehead** [comment]
> FlysystemOrphanageStorage you mean ?
Yes!

Hmm, that's obviously a mistake! 🙈

**Comment by bytehead** [comment]
I've reverted the changes in 8c101c8. Thank you for reporting!

**Pull request closed without merging**
