### PR TITLE
Added check for max_size: -1

### PR DESCRIPTION
**Pull request by n1ks2n**
Added fix to check max_size value, earlier no check leaded to max_size - 1 option that caused errors on file upload. refs #328

### CODE REVIEW

**Comment by bytehead** [comment]
Thanks! Is it possible to make all unrelated changes undone? It seems like some IDE auto-formatter was running while you've edited the relevant code.

**Comment by n1ks2n** [comment]
Ofc i can do this, just thought that it would be good to format code in PSR style as of PHP-FIG standard for open source and not only it. Just reply me and i will change it.

**Comment by bytehead** [comment]
The code style is given by the [php-cs-fixer](https://github.com/1up-lab/OneupUploaderBundle/blob/master/.php_cs.dist). It will get changed back anyway 🙂 Just for others to get the essential changed code quicker. Thank you!

**Comment by n1ks2n** [comment]
Ok, just didn't knew it cause there is no contribution guidelines =)

**Comment by bytehead** [comment]
No worries, you're contributions are welcome 👍

**Comment by n1ks2n** [comment]
Fixed style, left only my addition

**Comment by bytehead** [comment]
👍

**Pull request merged**
