### PR TITLE
Upload large files with flysystem

### PR DESCRIPTION
**Pull request by SrgSteak**
Fixes a memory problem that occurs when uploading large files.

### CODE REVIEW

**Comment by sheeep** [comment]
Does this work without registering stream wrappers?

**Comment by SrgSteak** [comment]
@sheeep i did not declare a stream wrapper in my config.

**Comment by SrgSteak** [comment]
Can i have an update on this one?
Will this PR be merged or not?

**Comment by sheeep** [comment]
Oh, you're actually right. I didn't realize the `fopen` was used for uploaded files only. Thank you for your contribution!

**Pull request merged**
