### PR TITLE
[RTM] Remove empty directories when cleaning up Orphanage

### PR DESCRIPTION
**Pull request by Schyzophrenic**
The empty directories were left over after a cleanup. 
This will check for empty directories and remove them.

### CODE REVIEW

**Comment by JHGitty** [comment]
@Schyzophrenic Please update this issue (Travis CI should not fail). Otherwise this PR might be closed.

**Comment by qzminski** [comment]
Could this feature be added in the next minor release?

**Comment by Schyzophrenic** [comment]
I am sorry I don't have the time to rebase it now.
Happy if someone can copy paste the code.

Le 15 sept. 2017 5:38 PM, "Kamil Kuzminski" <notifications@github.com> a
écrit :

**Comment by bytehead** [comment]
@Schyzophrenic I'll take care of that! Thanks for the PR 🙂

**Comment by bytehead** [comment]
Changes in bdef0e2.

**Pull request closed without merging**
