### PR TITLE
Fix PHP 7.1 Notice: A non well formed numeric value

### PR DESCRIPTION
**Pull request by mhlavac**
Notice: A non well formed numeric value encountered in /var/www/symfony/vendor/oneup/uploader-bundle/Oneup/UploaderBundle/DependencyInjection/OneupUploaderExtension.php on line 297

### CODE REVIEW

**Comment by bytehead** [comment]
Thank you!

**Comment by bytehead** [comment]
Sorry, had to revert. The unit tests doesn't work.

**Comment by mhlavac** [comment]
@bytehead no problem, I'll try to look into this today

**Comment by bytehead** [comment]
We need there actually a `string`-value from `trim`  (like `1k`, `1M`, `1G`).

**Comment by bytehead** [comment]
See here: https://travis-ci.org/1up-lab/OneupUploaderBundle/jobs/184173724#L447

**Pull request merged**
