### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by andreybolonin**

### CODE REVIEW

**Comment by bytehead** [comment]
Seems not to work:
```
7.3.0RC1 is not pre-installed; installing
Downloading archive: https://s3.amazonaws.com/travis-php-archives/binaries/ubuntu/14.04/x86_64/php-7.3.0RC1.tar.bz2
$ curl -s -o archive.tar.bz2 $archive_url && tar xjf archive.tar.bz2 --directory /
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now

$ phpenv global 7.3.0RC1
rbenv: version `7.3.0RC1' not installed
The command "phpenv global 7.3.0RC1" failed and exited with 1 during .
```

**Comment by andreybolonin** [comment]
@bytehead yep, you are right.

**Comment by daFish** [comment]
The notation is just `7.3` - this works as of a couple of days.

**Comment by andreybolonin** [comment]
Php 7.3 works in travis build matrix.
But waiting for merge https://github.com/KnpLabs/Gaufrette/pull/587

**Comment by bytehead** [comment]
PHP 7.3 is now available, but the tests still fail:
```
There was 1 error:
1) Oneup\UploaderBundle\Tests\Uploader\Chunk\Storage\GaufretteStorageTest::testExistanceOfTmpDir
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?
```
Would you mind to fix this before merge? 🙂

**Comment by bytehead** [comment]
Closing in favor of #369

**Pull request closed without merging**
