### PR TITLE
Changed request to master request

### PR DESCRIPTION
**Pull request by lsv**
* Changed request from container to request_stack
* Bumped symfony version to >=2.4 (thats were when request_stack got introduced)
* Changed some annotations so its now validates correctly in a IDE
* All tests are green

These changes are made so its now compatible with Symfony 2.4+ (also 3.0)

### CODE REVIEW

**Comment by lsv** [comment]
I added version compare to the "request getter", so it now also works with symfony 2.3

**Comment by JHGitty** [comment]
I think this line is not required:
https://github.com/lsv/OneupUploaderBundle/blob/1fd249208fd44bb89ebd93a21d8a7e6f2f9af505/Controller/AbstractChunkedController.php#L48

The ``$request`` is already passed through the function parameter.

**Comment by JHGitty** [comment]
:+1: Hope for fast merge.

**Comment by lsv** [comment]
I had to add symfony/http-kernel to composer otherwise symfony/framework-bundle would just download 2.8, and as http-kernel is the only place Symfony version is tagged it was needed for the version_compare, because request_stack is not in older versions than Symfony 2.4.

So now after adding this, Symfony 2.3 is still supported by this bundle

**Comment by bytehead** [comment]
@lsv @JHGitty Could you test the [release-1.4.0](https://github.com/1up-lab/OneupUploaderBundle/tree/release-1.4.0)-branch within your Symfony 3.0 applications? 

We had to remove the Symfony 2.3 support for this particular release.

**Comment by JHGitty** [comment]
@bytehead Works fine. :+1:

**Comment by bytehead** [comment]
@lsv Thanks a lot for your contribution!

**Pull request merged**
