### PR TITLE
Adding Plupload's error handler

### PR DESCRIPTION
**Pull request by MJBGO**
Added an ErrorHandler for Plupload.

It only needs an error message so it can be handled client side.

### CODE REVIEW

**Comment by JHGitty** [comment]
@MJBGO Please update this PR (Travis CI should not fail). Otherwise this PR might be closed.

**Comment by MJBGO** [comment]
It is not due to my code

> Cloning into '1up-lab/OneupUploaderBundle'...
fatal: unable to connect to github.com:
github.com: Temporary failure in name resolution

**Comment by JHGitty** [comment]
@bytehead Are you able to restart Travis CI on this PR?

**Comment by bytehead** [comment]
Thanks! Will be in the next release (`1.9.0`).

**Pull request merged**
