### PR TITLE
Support for flysystem v2

### LINKED ISSUE #404: Error whila upoloading with Symfony 5.2
### Question

|  boundle | version
|------------ | ------
| symfony | 5.2.6
| oneup/flysystem-bundle | 4.0.6
| oneup/uploader-bundle | 3.1.2

Made an upgrade to `Oneup Flysystem` and `Oneup Uploader` in order to use latest `Flysystem v2`!
Yet i am getting an error while uploading files.

`Argument 1 passed to Oneup\UploaderBundle\Uploader\Storage\FlysystemStorage::__construct() must be an instance of League\Flysystem\FilesystemInterface, instance of League\Flysystem\Filesystem given, called in D:\DEV\Izstrade_WEB_DEV\_DEV_SF5_\zenfiles5\var\cache\dev\Container9LbNvYG\getOneupUploader_Controller_GalleryService.php on line 28`

> relevant part of services.yaml

```
    oneup_flysystem.gallery_filesystem:
        alias: League\Flysystem\Filesystem
        public: true

    League\Flysystem\Local\LocalFilesystemAdapter: '@oneup_flysystem.adapter.local'
    League\Flysystem\MountManager: '@oneup_flysystem.mount_manager'
```

> my oneup_uploader.yaml

```
oneup_uploader:
    mappings:
        gallery:
            storage:
                type: flysystem
                filesystem: oneup_flysystem.gallery_filesystem

            frontend: blueimp
            enable_progress: true
            namer: app.upload_unique_namer

            max_size: !php/const App\Entity\AppConstants::UPLOADABLE_FILE_SIZE_MAX
```

> my oneup_flysystem.yaml

```
oneup_flysystem:
    adapters:
        my_adapter:
            local:
                location: '%data_dir_stored%'

    filesystems:
        default_filesystem:
            adapter: my_adapter
            alias: League\Flysystem\Filesystem
```

I tried changing `League\Flysystem\Filesystem` referrences in YAML to `League\Flysystem\FilesystemInterface`.
It has no effect - the same error persists.

It might be misconfiguration issue or a bug.

Any help would be appreciated, thank you!

### PR DESCRIPTION
**Pull request by m2mtech**
adds support for [flysystem v2](https://github.com/thephpleague/flysystem)

fixes #404 

Please note, while flysystem works starting from php 7.2, [OneupFlysystemBundle](https://github.com/1up-lab/OneupFlysystemBundle) requires at least php 7.4. Thus, the workflow also needed adjustment.

### bc-break 
- dropped support for php <7.4 (due to OneupFlysystemBundle v4.x)
- dropped support for flysystem v1.x (not compatible with v2)
- dropped support for OneupFlysystemBundle < v4 (requires flysystem v1.x)

### CODE REVIEW

**Comment by bytehead** [comment]
Thank you very much! This is lovely ❤️ I'll look into it the next days!

**Review by bytehead — APPROVED** [review]

**Comment by aless673** [comment]
Please merge it ! Big thanks to you @m2mtech

**Comment by Rikijs** [comment]
Hello!
Is there something necessary in order to merge changes in this PR?

**Comment by dlakomski** [comment]
Is this PR going to be merged? It keeps us from upgrade to Symfony 6.

**Comment by bytehead** [comment]
Thank you very much @m2mtech!

**Pull request merged**
