### PR TITLE
Fix unnamed directory when uploading to Amazon S3

### PR DESCRIPTION
**Pull request by diegotham**

### CODE REVIEW

**Comment by JHGitty** [comment]
This PR is related to issue #241.

**Comment by redayoub** [comment]
when will this be merged, please ?

**Comment by bytehead** [comment]
Why do you trim the slash on the very left instead of the very right one? 
See also [your comment](https://github.com/1up-lab/OneupUploaderBundle/issues/241#issuecomment-207382122).

**Comment by diegotham** [comment]
It's the left one that creates the empty directory. You can read about it in the official documentation: http://docs.aws.amazon.com/AmazonS3/latest/UG/FolderOperations.html

If you set a folder like /myfolder, it will be //myfolder, it has to be just myfolder. If you set no directory, you should not use a trailing slash, because it creates an empty one.

**Pull request merged**
