### PR TITLE
Fixed various deprecation fixes for Symfony >6.1, some code changes for PHP >= 8.0

### PR DESCRIPTION
**Pull request by joesenova**
1. Implemented the AsCommand attributes for final $defaultName
3. Removed support for PHP <8.0
4. Reworked the __construct methods to be on-par with php >=8.0
5. Removed all rferences to GetMasterRequest - using only getMainRequest now
6. Fixed custom_uploader.md documentation to use getMainRequest

We might need to bump the major package version due to dropping php v7 support with these changes

### CODE REVIEW

**Comment by joesenova** [comment]
There are some issues I am trying to solve here.

I have not got lots of knowledge with the github actions and the actions it runs.
If you know how to help me with this, please do let me know.

Thanks

**Comment by joesenova** [comment]
Wait:

Here is codebase that has all the above fixed already.

https://github.com/dlxmedia/OneupUploaderBundle

**Comment by bytehead** [comment]
Yes, that's the code from #432 (but closed unfortunately). I'll have look at yours 👍

**Comment by joesenova** [comment]
Let me know what is needed here.

Thanks

**Comment by evertharmeling** [comment]
Any update on this PR? As Symfony 7 is released shortly ([end nov 2023](https://symfony.com/releases)) it would be nice to have this going forward and add support for Symfony 7.

If there's any help needed, let me know.

**Comment by evertharmeling** [comment]
Not sure how I could add it to this PR, but made a new one https://github.com/1up-lab/OneupUploaderBundle/pull/436

**Comment by bytehead** [comment]
Closing this in favor of #436 (your precious work is included in there, thank you very much @joesenova!)

**Pull request closed without merging**
