### PR TITLE
Custom subfolder / Custom data in the namer

### PR DESCRIPTION
**Pull request by nomadOnWeb**
Hello !
Here is a simple way to allow a user to set a custom subfolder.
It works with the Request object, sent to the NamerInterface.
With this little improvement we're able to send any custom data to the Namer.
By default, the OneUp UniqIdNamer will check for a "subfolder" named data. If it's found, subfolder is added to the name.

This improvement let also the user to send any data, like a dynamic string to use in his own custom namer. 3 lines of code for a feature I think everyone wants :)

PS : Docs updated in the commits, but Im french and my english is not perfect :p

### CODE REVIEW

**Comment by sheeep** [comment]
I don't really get it sorry. You can pass the `RequestStack` object to your namer service if you really need it. Or do I miss something here? :)

**Comment by nomadOnWeb** [comment]
Hello,
first of all, Im not a symfony expert, just a random user, so maybe it's me who dont get it.

@lsv I guess I just commit the needed modifications. (but I dont really understand "add which class gets injected", what do you mean by this ? A Request object is injected, as it is explain with the "use" statement no?) Sorry if I act like a noob :s 

@sheeep First I didn't know RequestStack :s But yes the request can be injected in the service (and by the way I guess the custom namer can't extend the OneUp NamerInterface... or am I wrong? It's not a big deal through).
But I was guessing the main goal of OneUp Uploader is to provide features to easily implement file Uploading. Here im only making the way easier for a random user. I saw people were researching (like me) a way to have a dynamic subfolder (like a subfolder for each "product" to have one folder per gallery) ([Issue #156](https://github.com/1up-lab/OneupUploaderBundle/issues/156), [Issue #129](https://github.com/1up-lab/OneupUploaderBundle/issues/129) and on stackoverflow).
So im just trying to contribute as I can, even if I cant do a lot. Feel free to delete this PR if my idea isn't a needed feature :)

**Comment by lsv** [comment]
@sheeep The request stack does not get injected in the handleUpload method, the request from the request stack is retracted from the controller of the current used implementation.

Fx from [dropzone](https://github.com/1up-lab/OneupUploaderBundle/blob/master/Controller/DropzoneController.php), the request get retracted from the request stack in the upload method, which then calls the handleUpload method, with only the request.

@nomadOnWeb Yep, I can see I have made a comment to a outdated commit, and fine you also have added the request to the annotation, so IDE's dont get confused ;-)

**Comment by nomadOnWeb** [comment]
@lsv oh yeah right, first I forgot it so I added it in another commit ^^ Im still learning how to use github haha

**Comment by JHGitty** [comment]
It is *not* a professional way to add this code to each namer class:
```php
if ($subfolder = $request->get('subfolder')) $subfolder .= '/'
```

No developer of a new namer class like to add this code to their own class to support subfolders. We need to fix the subfolder issue globally on the bundle for all namers without adding code to the namer classes itself.

**Comment by nomadOnWeb** [comment]
I agree! Request in the namer class can have a largest field than what I was thinking in my application. Im closing this PR ;)

**Pull request closed without merging**
