### PR TITLE
Let's see if this gets us symfony 2.6 support.

### PR DESCRIPTION
**Pull request by mvrhov**
It seems that there are some restrictions somewhere.. however I'm unable to figure it out. It might help or not.
A I'm unable to install this bundle in sf2.6 project because of dependency problems...

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove symfony/symfony v2.6.1
    - don't install symfony/routing v2.4.10|don't install symfony/symfony v2.6.1
    - don't install symfony/symfony v2.6.1|remove symfony/routing v2.4.10
    - Installation request for symfony/symfony == 2.6.1.0 -> satisfiable by symfony/symfony[v2.6.1].
    - Installation request for symfony/routing == 2.4.10.0 -> satisfiable by symfony/routing[v2.4.10].
```

### CODE REVIEW

**Comment by mvrhov** [comment]
ping

**Comment by sheeep** [comment]
I'll take a look. Thanks for reporting.

**Comment by sheeep** [comment]
@mvrhov Can you provide a few more details? I just tried to install the bundle on a clean 2.6, and it seems to work.

```
$ composer create-project symfony/framework-standard-edition path/
Installing symfony/framework-standard-edition (v2.6.4)
  - Installing symfony/framework-standard-edition (v2.6.4)
    Downloading: 100%

[...]
```

Then I added `"oneup/uploader-bundle": "@stable"` to my composer file and once again updated the installation:

```
⇢ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing sensio/generator-bundle (v2.5.1)
  - Installing sensio/generator-bundle (v2.5.2)
    Downloading: 100%         

  - Installing oneup/uploader-bundle (v1.3.1)
    Loading from cache
```

Furthermore, take a look at the [Composer documentation](https://getcomposer.org/doc/01-basic-usage.md#package-versions).

`>=2.2` is less restrictive than `~2.2`, so I doubt it will solve your problem.
Are you sure the dependencies of this bundle fails the installation? Or could it be another problem?

**Comment by mvrhov** [comment]
"symfony/symfony": "~2.6" is my symfony version and "oneup/uploader-bundle": "~1.3". I cannot figure out what would be wrong, but thats what composer outputs. It doesn't work even if I replace ~1.3 with stable. I still get the same output.
It would work if I do `composer update` but I don't want to do that. It seems that It's time to bring the composer team into this as it seem that there is a composer bug.

**Pull request closed without merging**
