### PR TITLE
Added a boolean (default false) parameter on mapping config called root_folder.

### PR DESCRIPTION
**Pull request by nathanmarcos**
When true, remove the mapping name folder from upload directory.

### CODE REVIEW

**Comment by bytehead** [comment]
Thanks for your PR!
What's the use case for this change?

**Comment by nathanmarcos** [comment]
Hello @bytehead! We have a predefined folder structure to save the files and photos uploaded by the users in the server. All the paths are generated dynamically but, a new folder was created with the mapping name that was breaking our structure. Having the possibility to avoid the folder called the "mapping name" we can avoid this problem.

**Comment by sheeep** [comment]
Hey @nathanmarcos 

Thanks for the addition. Sorry to break your file system structure, we now it ourself that sometimes you're forced to live with strange requirements. Could you add a little addition to the documentation? Afterwards I'll merge this PR.

**Comment by nathanmarcos** [comment]
Hello @sheeep 

I made the changes in the docs about the new config parameter. 
Thanks for accept my PR!

**Comment by nathanmarcos** [comment]
Ping @bytehead @sheeep

**Comment by bytehead** [comment]
Merged in https://github.com/1up-lab/OneupUploaderBundle/commit/eb609baf31012cf67fb776953bdee2bd484e58eb.

**Pull request closed without merging**
